name: adjusted_html_view_web
description: This package provides to the HtmlView with adjusted height and natural displaying on the Web.
version: 0.0.3
homepage: https://github.com/organic-nailer/adjusted_html_view_web

environment:
  sdk: ">=2.16.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.0.0
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.2
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  plugin:
    platforms:
      web:
        pluginClass: AdjustedHtmlViewPlugin
        fileName: adjusted_html_view_web.dart
